version: "3.9"
services:
  qbittorrent-nox:
    container_name: qbittorrent-nox
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
      - QBT_EULA="accept"
    image: qbittorrentofficial/qbittorrent-nox:latest
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "8080:8080/tcp"
    volumes:
      - ./config:/config
      - /mnt/ssd/downloads:/downloads
    tty: true