services:
  cache:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning

  bot:
    container_name: kinozal_bot
    depends_on:
      - cache
    build: .
    restart: always
    command:
      - infisical
      - run
      - --domain=https://env.nidzh.com
      - --projectId=${PROJECT_ID}
      - --env=${INFISICAL_ENV}
      - --
      - uv
      - run
      - uvicorn
      - bot.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
    env_file:
      - .env
    stdin_open: true # docker run -i
    networks:
      - nginx
      - default

volumes:
  cache:
    driver: local

networks:
  nginx:
    name: nginx-network
    external: true
