name: Deploy to VDS Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.INFISICAL_SERVER_HOST }}
          username: ${{ secrets.INFISICAL_SERVER_USER }}
          key: ${{ secrets.INFISICAL_SERVER_SSH_KEY }}
          source: "src,Dockerfile,docker-compose.yaml,pyproject.toml,uv.lock"
          target: ~/kinozal-bot

      - name: Restart Docker Compose
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.INFISICAL_SERVER_HOST }}
          username: ${{ secrets.INFISICAL_SERVER_USER }}
          key: ${{ secrets.INFISICAL_SERVER_SSH_KEY }}
          script: |
            cd ~/kinozal-bot
            docker compose down
            docker compose up -d --build
